# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-14 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(choices=[('master', '\u30de\u30b9\u30bf\u30fc'), ('slave', '\u30b9\u30ec\u30fc\u30d6')], default='master', max_length=64, verbose_name='\u5c5e\u6027')),
                ('name', models.CharField(max_length=256, verbose_name='\u540d\u524d')),
                ('url', models.CharField(max_length=512, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='ScraperData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selector', models.CharField(max_length=256, verbose_name='CSS\u30bb\u30ec\u30af\u30bf')),
                ('target', models.CharField(choices=[('no_target', '\u4f55\u3082\u53d6\u5f97\u3057\u306a\u3044'), ('text', '\u672c\u6587'), ('src', 'src\u5c5e\u6027\u5024'), ('href', 'href\u5c5e\u6027\u5730')], default='no_target', max_length=64, verbose_name='\u53d6\u5f97\u5bfe\u8c61')),
                ('name', models.CharField(max_length=256, verbose_name='\u540d\u524d')),
                ('trigger_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrango.CrawlerData')),
                ('trigger_s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrango.ScraperData')),
            ],
        ),
    ]
