# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-15 13:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selector', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u64cd\u4f5c\u5bfe\u8c61name\u5c5e\u6027')),
                ('action_type', models.CharField(choices=[('', '\u4f55\u3082\u3057\u306a\u3044'), ('input', '\u5165\u529b'), ('click', '\u30af\u30ea\u30c3\u30af'), ('reload', '\u30ea\u30ed\u30fc\u30c9'), ('enter_iframe', 'iframe\u306b\u5165\u308b'), ('drag_and_drop', '\u30c9\u30e9\u30c3\u30b0\u30a2\u30f3\u30c9\u30c9\u30ed\u30c3\u30d7'), ('upload_file', '\u30d5\u30a1\u30a4\u30eb\u30a2\u30c3\u30d7\u30ed\u30fc\u30c9')], default='', max_length=64, verbose_name='\u30a2\u30af\u30b7\u30e7\u30f3\u30bf\u30a4\u30d7')),
                ('content', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5165\u529b\u5185\u5bb9')),
                ('valid', models.BooleanField(default=True, verbose_name='\u6709\u52b9')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u8aac\u660e')),
            ],
        ),
        migrations.CreateModel(
            name='ChatAPIData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='\u4f5c\u6210\u65e5\u6642')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u30e6\u30fc\u30b6\u30fc\u540d')),
                ('description', models.CharField(blank=True, max_length=512, null=True, verbose_name='\u8aac\u660e')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResultData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, choices=[('success', '\u6b63\u5e38\u7d42\u4e86'), ('failure', '\u5931\u6557')], default='', max_length=64, verbose_name='\u53ef\u5426')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6642\u523b')),
                ('log', models.TextField(blank=True, null=True)),
                ('result_data', models.TextField()),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'ordering': ('-datetime',),
            },
        ),
        migrations.CreateModel(
            name='ScraperData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='\u4f5c\u6210\u65e5\u6642')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='\u540d\u524d')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('state', models.CharField(choices=[('executing', '\u5b9f\u884c\u4e2d'), ('active', '\u6b63\u5e38'), ('error', '\u7570\u5e38')], default='active', editable=False, max_length=64, verbose_name='\u72b6\u614b')),
                ('repetition', models.CharField(blank=True, choices=[('', 'OFF'), ('30', '30\u79d2'), ('60', '1\u5206'), ('300', '5\u5206'), ('600', '10\u5206'), ('1800', '30\u5206'), ('3600', '1\u6642\u9593'), ('10800', '3\u6642\u9593'), ('21600', '6\u6642\u9593'), ('43200', '12\u6642\u9593')], max_length=64, verbose_name='\u5b9a\u671f\u5b9f\u884c')),
                ('screenshot', models.CharField(blank=True, choices=[('', 'OFF'), ('(1280px,720px)', '\u30b9\u30de\u30db\u30b5\u30a4\u30ba'), ('(1280px,980px)', 'PC\u30b5\u30a4\u30ba')], max_length=64, verbose_name='\u30b9\u30af\u30ea\u30fc\u30f3\u30b7\u30e7\u30c3\u30c8')),
                ('notification_cond', models.CharField(choices=[('always', '\u5e38\u6642'), ('changed', '\u5909\u5316\u6642'), ('ss_changed', '\u30b9\u30af\u30ea\u30fc\u30f3\u30b7\u30e7\u30c3\u30c8\u5909\u5316\u6642'), ('ss_changed2', '\u30b9\u30af\u30ea\u30fc\u30f3\u30b7\u30e7\u30c3\u30c8\u5909\u5316\u6642(\u611f\u5ea6\u4f4e)')], default='always', max_length=64, verbose_name='\u901a\u77e5\u6761\u4ef6')),
                ('last_execute_time', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='\u6700\u8fd1\u306e\u5b9f\u884c\u65e5\u6642')),
                ('user_agent', models.CharField(choices=[('Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0', '\u81ea\u52d5'), ('Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0', 'Firefox'), ('Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36 ', 'GoogleChrome'), ('Mozilla/5.0 (iPad; CPU OS 11_2_1 like Mac OS X) AppleWebKit/604.4.7 (KHTML, like Gecko) Version/11.0 Mobile/15C153 Safari/604.1', 'Safari(ipad)'), ('Mozilla/5.0 (Macintosh; U; PPC Mac OS X; ja-jp) AppleWebKit/85.7 (KHTML, like Gecko) Safari/85.6 ', 'Safari(mac)'), ('Mozilla/5.0 (Android 4.4; Mobile; rv:41.0) Gecko/41.0 Firefox/41.0', 'Firefox(Android)'), ('Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_5 like Mac OS X) AppleWebKit/604.5.2 (KHTML, like Gecko) Version/11.0 Mobile/15D5046b Safari/604.1', 'iphone')], default='Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0', max_length=255, verbose_name='\u30e6\u30fc\u30b6\u30fc\u30a8\u30fc\u30b8\u30a7\u30f3\u30c8')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScraperInfoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selector', models.CharField(max_length=255, verbose_name='CSS\u30bb\u30ec\u30af\u30bf')),
                ('target', models.CharField(blank=True, choices=[('', '\u898b\u3064\u3051\u308b\u3060\u3051'), ('html', 'HTML'), ('text', '\u672c\u6587'), ('src', 'src\u5c5e\u6027\u5024'), ('href', 'href\u5c5e\u6027\u5730')], default='html', max_length=64, null=True, verbose_name='\u53d6\u5f97\u5bfe\u8c61')),
                ('name', models.CharField(max_length=255, verbose_name='\u540d\u524d')),
                ('scraper_name', models.CharField(blank=True, max_length=255, verbose_name='\u30b9\u30af\u30ec\u30a4\u30d1\u30fc\u540d')),
                ('valid', models.BooleanField(default=True, verbose_name='\u6709\u52b9')),
                ('master_scraper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scrango.ScraperInfoData', verbose_name='\u3053\u308c\u3092\u898b\u3064\u3051\u305f\u3089\u5b9f\u884c')),
                ('scraper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrango.ScraperData')),
            ],
        ),
        migrations.CreateModel(
            name='WebAPIData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='\u4f5c\u6210\u65e5\u6642')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='\u540d\u524d')),
                ('url', models.URLField(verbose_name='URL')),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], max_length=32, verbose_name='HTTP\u30e1\u30bd\u30c3\u30c9')),
                ('repetition', models.CharField(blank=True, choices=[('', 'OFF'), ('30', '30\u79d2'), ('60', '1\u5206'), ('300', '5\u5206'), ('600', '10\u5206'), ('1800', '30\u5206'), ('3600', '1\u6642\u9593'), ('10800', '3\u6642\u9593'), ('21600', '6\u6642\u9593'), ('43200', '12\u6642\u9593')], max_length=64, verbose_name='\u5b9a\u671f\u5b9f\u884c')),
                ('notification_cond', models.CharField(choices=[('always', '\u5e38\u6642'), ('changed', '\u5909\u5316\u6642'), ('ss_changed', '\u30b9\u30af\u30ea\u30fc\u30f3\u30b7\u30e7\u30c3\u30c8\u5909\u5316\u6642'), ('ss_changed2', '\u30b9\u30af\u30ea\u30fc\u30f3\u30b7\u30e7\u30c3\u30c8\u5909\u5316\u6642(\u611f\u5ea6\u4f4e)')], default='always', max_length=64, verbose_name='\u901a\u77e5\u6761\u4ef6')),
                ('last_execute_time', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='\u6700\u8fd1\u306e\u5b9f\u884c\u65e5\u6642')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebAPIHttpHeaderParameterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='name')),
                ('value', models.CharField(max_length=512, verbose_name='value')),
                ('webapi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrango.WebAPIData')),
            ],
        ),
        migrations.CreateModel(
            name='WebAPIParameterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='name')),
                ('value', models.CharField(max_length=512, verbose_name='value')),
                ('webapi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrango.WebAPIData')),
            ],
        ),
        migrations.CreateModel(
            name='WebAPIResultData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, choices=[('success', '\u6b63\u5e38\u7d42\u4e86'), ('failure', '\u5931\u6557')], default='', max_length=64, verbose_name='\u53ef\u5426')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6642\u523b')),
                ('log', models.TextField(blank=True, null=True)),
                ('result_data', models.TextField()),
                ('webapi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrango.WebAPIData')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChatworkAPIData',
            fields=[
                ('chatapidata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scrango.ChatAPIData')),
                ('api_key', models.CharField(max_length=255, verbose_name='API Token')),
                ('roomid', models.CharField(max_length=128, verbose_name='roomid')),
            ],
            options={
                'abstract': False,
            },
            bases=('scrango.chatapidata',),
        ),
        migrations.CreateModel(
            name='LineAPIData',
            fields=[
                ('chatapidata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scrango.ChatAPIData')),
                ('access_token', models.CharField(max_length=255, verbose_name='\u30a2\u30af\u30bb\u30b9\u30c8\u30fc\u30af\u30f3')),
            ],
            options={
                'abstract': False,
            },
            bases=('scrango.chatapidata',),
        ),
        migrations.CreateModel(
            name='SlackAPIData',
            fields=[
                ('chatapidata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scrango.ChatAPIData')),
                ('webhook_url', models.URLField(verbose_name='Webhook URL')),
                ('token', models.CharField(blank=True, max_length=512, null=True, verbose_name='Token(\u753b\u50cf\u9001\u4fe1API)')),
                ('channel_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ChannelID(\u753b\u50cf\u9001\u4fe1API)')),
            ],
            options={
                'abstract': False,
            },
            bases=('scrango.chatapidata',),
        ),
        migrations.CreateModel(
            name='TwitterAPIData',
            fields=[
                ('chatapidata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scrango.ChatAPIData')),
                ('consumer_key', models.CharField(max_length=255, verbose_name='Consumer Key')),
                ('consumer_secret', models.CharField(max_length=255, verbose_name='Consumer Secret')),
                ('access_token', models.CharField(max_length=255, verbose_name='Access Token')),
                ('access_token_secret', models.CharField(max_length=255, verbose_name='Access Token Secret')),
            ],
            options={
                'abstract': False,
            },
            bases=('scrango.chatapidata',),
        ),
        migrations.AddField(
            model_name='webapidata',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scrango.ChatAPIData'),
        ),
        migrations.AddField(
            model_name='scraperdata',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scrango.ChatAPIData'),
        ),
        migrations.AddField(
            model_name='resultdata',
            name='scraper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrango.ScraperData'),
        ),
        migrations.AddField(
            model_name='chatapidata',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actiondata',
            name='scraper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrango.ScraperData'),
        ),
    ]
