# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-19 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperdata',
            name='selenium_mode',
            field=models.BooleanField(default=False, verbose_name='Javascript\u5b9f\u884c\u30e2\u30fc\u30c9'),
        ),
    ]
