# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-27 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrango', '0002_scraperdata_selenium_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webapihttpheaderparameterdata',
            name='value',
            field=models.TextField(verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='webapiparameterdata',
            name='value',
            field=models.TextField(verbose_name='value'),
        ),
    ]
