# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-14 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrango', '0003_auto_20180514_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperdata',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrango.ScraperData'),
        ),
        migrations.AlterField(
            model_name='scraperdata',
            name='target',
            field=models.CharField(choices=[('html', 'HTML'), ('text', '\u672c\u6587'), ('src', 'src\u5c5e\u6027\u5024'), ('href', 'href\u5c5e\u6027\u5730')], default='html', max_length=64, verbose_name='\u53d6\u5f97\u5bfe\u8c61'),
        ),
    ]
