# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-14 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrango', '0004_auto_20180514_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scraperdata',
            old_name='trigger_c',
            new_name='crawler',
        ),
        migrations.RemoveField(
            model_name='scraperdata',
            name='level',
        ),
        migrations.AddField(
            model_name='scraperdata',
            name='master_scraper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrango.ScraperData', verbose_name='\u3053\u308c\u3092\u898b\u3064\u3051\u305f\u3089\u5b9f\u884c'),
        ),
    ]
