# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-14 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scrango', '0005_auto_20180514_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u5b9f\u884c\u6642\u9593')),
                ('json', models.TextField(blank=True, editable=False)),
                ('crawler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrango.CrawlerData')),
            ],
        ),
    ]
