# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-16 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrango', '0008_auto_20180516_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperdata',
            name='crawler_name',
            field=models.CharField(blank=True, max_length=256, verbose_name='\u30af\u30ed\u30fc\u30e9\u30fc\u540d'),
        ),
    ]
