# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-17 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrango', '0009_scraperdata_crawler_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlerdata',
            name='repetition_interval',
            field=models.CharField(blank=True, choices=[('', 'OFF'), ('30sec', '30\u79d2'), ('1min', '1\u5206'), ('10min', '10\u5206'), ('30min', '30\u5206'), ('1hour', '1\u6642\u9593'), ('12hour', '12\u6642\u9593')], max_length=64, verbose_name='\u5b9a\u671f\u5b9f\u884c'),
        ),
        migrations.AlterField(
            model_name='crawlerdata',
            name='url',
            field=models.CharField(blank=True, max_length=512, verbose_name='URL'),
        ),
    ]
