# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-17 06:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrango', '0010_auto_20180517_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crawlerdata',
            old_name='repetition_interval',
            new_name='repetition',
        ),
    ]
