# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrango', '0011_auto_20180517_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlerdata',
            name='screenshot',
            field=models.BooleanField(default=False, verbose_name='\u30b9\u30af\u30ea\u30fc\u30f3\u30b7\u30e7\u30c3\u30c8'),
        ),
        migrations.AddField(
            model_name='resultdata',
            name='screenshot',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='crawlerdata',
            name='repetition',
            field=models.CharField(blank=True, choices=[('', 'OFF'), ('30sec', '30\u79d2'), ('1min', '1\u5206'), ('5min', '5\u5206'), ('10min', '10\u5206'), ('30min', '30\u5206'), ('1hour', '1\u6642\u9593'), ('12hour', '12\u6642\u9593')], max_length=64, verbose_name='\u5b9a\u671f\u5b9f\u884c'),
        ),
    ]
