# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrango', '0012_auto_20180518_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlerdata',
            name='screenshot',
            field=models.CharField(blank=True, max_length=64, verbose_name='\u30b9\u30af\u30ea\u30fc\u30f3\u30b7\u30e7\u30c3\u30c8'),
        ),
    ]
