# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrango', '0014_auto_20180518_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlerdata',
            name='notification',
            field=models.CharField(blank=True, choices=[('', '\u901a\u77e5\u3057\u306a\u3044'), ('slack', 'slack'), ('chatwork', 'chatwork')], max_length=64, verbose_name='\u901a\u77e5\u5148'),
        ),
        migrations.AlterField(
            model_name='resultdata',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
