# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrango', '0015_auto_20180518_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperdata',
            name='valid',
            field=models.BooleanField(default=True, verbose_name='\u6709\u52b9'),
        ),
    ]
