# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrango', '0016_scraperdata_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlerdata',
            name='last_execute_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u6700\u8fd1\u306e\u5b9f\u884c\u65e5\u6642'),
        ),
        migrations.AlterField(
            model_name='crawlerdata',
            name='repetition',
            field=models.CharField(blank=True, choices=[('', 'OFF'), ('30', '30\u79d2'), ('60', '1\u5206'), ('300', '5\u5206'), ('600', '10\u5206'), ('1800', '30\u5206'), ('3600', '1\u6642\u9593'), ('10800', '3\u6642\u9593'), ('21600', '6\u6642\u9593'), ('43200', '12\u6642\u9593')], max_length=64, verbose_name='\u5b9a\u671f\u5b9f\u884c'),
        ),
    ]
