# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrango', '0017_auto_20180518_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlerdata',
            name='state',
            field=models.CharField(choices=[('executing', '\u5b9f\u884c\u4e2d'), ('active', '\u6b63\u5e38'), ('error', '\u7570\u5e38')], default='active', editable=False, max_length=64, verbose_name='\u72b6\u614b'),
        ),
    ]
