# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrango', '0018_auto_20180518_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawlerdata',
            name='attribute',
        ),
    ]
