# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrango', '0019_remove_crawlerdata_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlerdata',
            name='last_execute_time',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='\u6700\u8fd1\u306e\u5b9f\u884c\u65e5\u6642'),
        ),
    ]
