# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrango', '0020_auto_20180519_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlerdata',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='\u8aac\u660e'),
        ),
        migrations.AlterField(
            model_name='crawlerdata',
            name='notification',
            field=models.CharField(blank=True, choices=[('', '\u672a\u8a2d\u5b9a'), ('slack', 'slack'), ('chatwork', 'chatwork')], max_length=64, verbose_name='\u901a\u77e5\u5148'),
        ),
        migrations.AlterField(
            model_name='crawlerdata',
            name='screenshot',
            field=models.CharField(blank=True, choices=[('', 'OFF'), ('(1280px,720px)', '\u30b9\u30de\u30db\u30b5\u30a4\u30ba'), ('(1280px,980px)', 'PC\u30b5\u30a4\u30ba')], max_length=64, verbose_name='\u30b9\u30af\u30ea\u30fc\u30f3\u30b7\u30e7\u30c3\u30c8'),
        ),
    ]
