# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-31 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrango', '0022_actiondata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperdata',
            name='target',
            field=models.CharField(choices=[('', '\u898b\u3064\u3051\u308b\u3060\u3051'), ('html', 'HTML'), ('text', '\u672c\u6587'), ('src', 'src\u5c5e\u6027\u5024'), ('href', 'href\u5c5e\u6027\u5730')], default='html', max_length=64, verbose_name='\u53d6\u5f97\u5bfe\u8c61'),
        ),
    ]
