# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-01 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrango', '0024_auto_20180531_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiondata',
            name='action_type',
            field=models.CharField(choices=[('', '\u4f55\u3082\u3057\u306a\u3044'), ('input', '\u5165\u529b'), ('click', '\u30af\u30ea\u30c3\u30af'), ('reload', '\u30ea\u30ed\u30fc\u30c9')], default='', max_length=64, verbose_name='\u30a2\u30af\u30b7\u30e7\u30f3\u30bf\u30a4\u30d7'),
        ),
        migrations.AlterField(
            model_name='actiondata',
            name='selector',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='\u64cd\u4f5c\u5bfe\u8c61name\u5c5e\u6027'),
        ),
    ]
