# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-01 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrango', '0025_auto_20180601_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiondata',
            name='action_type',
            field=models.CharField(choices=[('', '\u4f55\u3082\u3057\u306a\u3044'), ('input', '\u5165\u529b'), ('click', '\u30af\u30ea\u30c3\u30af'), ('reload', '\u30ea\u30ed\u30fc\u30c9'), ('drag_and_drop', '\u30c9\u30e9\u30c3\u30b0\u30a2\u30f3\u30c9\u30c9\u30ed\u30c3\u30d7')], default='', max_length=64, verbose_name='\u30a2\u30af\u30b7\u30e7\u30f3\u30bf\u30a4\u30d7'),
        ),
    ]
