# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-05 01:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrango', '0029_auto_20180605_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperdata',
            name='master_scraper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scrango.ScraperData', verbose_name='\u3053\u308c\u3092\u898b\u3064\u3051\u305f\u3089\u5b9f\u884c'),
        ),
    ]
