# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-05 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrango', '0031_auto_20180605_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatapidata',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='\u8aac\u660e'),
        ),
    ]
