# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-06 01:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrango', '0032_chatapidata_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatapidata',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='\u4f5c\u6210\u65e5\u6642'),
        ),
        migrations.AddField(
            model_name='chatapidata',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crawlerdata',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='\u4f5c\u6210\u65e5\u6642'),
        ),
        migrations.AddField(
            model_name='crawlerdata',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
