# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-06 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scrango', '0033_auto_20180606_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlerdata',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='crawlerdata',
            name='url',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='URL'),
        ),
    ]
