# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-06 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrango', '0034_auto_20180606_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlerdata',
            name='notification_cond',
            field=models.CharField(choices=[('always', '\u5e38\u6642'), ('changed', '\u5909\u5316\u6642'), ('ss_changed', '\u30b9\u30af\u30ea\u30fc\u30f3\u30b7\u30e7\u30c3\u30c8\u5909\u5316\u6642'), ('ss_changed2', '\u30b9\u30af\u30ea\u30fc\u30f3\u30b7\u30e7\u30c3\u30c8\u5909\u5316\u6642(\u611f\u5ea6\u4f4e)')], default='always', max_length=64, verbose_name='\u901a\u77e5\u6761\u4ef6'),
        ),
        migrations.AlterField(
            model_name='crawlerdata',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scrango.ChatAPIData'),
        ),
    ]
