# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-06 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scrango', '0035_auto_20180606_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlerdata',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
