# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-06 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scrango', '0036_auto_20180606_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlerdata',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
