# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-07 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrango', '0037_auto_20180606_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultdata',
            name='log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
