# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_name', models.CharField(max_length=256, verbose_name='\u5165\u529b\u6b04\u306ename\u5c5e\u6027\u540d')),
                ('input_type', models.CharField(choices=[('kana', '\u3072\u3089\u304c\u306a'), ('katakana', '\u30ab\u30bf\u30ab\u30ca'), ('kanji', '\u6f22\u5b57'), ('alpha', '\u30a2\u30eb\u30d5\u30a1\u30d9\u30c3\u30c8'), ('num', '\u6570\u5b57'), ('phone', '\u96fb\u8a71\u756a\u53f7'), ('mail', '\u30e1\u30fc\u30eb\u30a2\u30c9\u30ec\u30b9')], max_length=64, verbose_name='\u5165\u529b\u5185\u5bb9')),
                ('parent_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangolla.FormData')),
            ],
        ),
    ]
