# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangolla', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logdata',
            old_name='uuid',
            new_name='manager',
        ),
    ]
