# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-21 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('djangolla', '0002_auto_20180420_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmanagedata',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u53d7\u4fe1\u6642\u9593'),
        ),
        migrations.AlterField(
            model_name='logdata',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u53d7\u4fe1\u6642\u9593'),
        ),
    ]
