# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-05 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangolla', '0004_auto_20180605_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmanagedata',
            name='uuid',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
    ]
