# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-03 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=512, verbose_name='URL')),
                ('name', models.CharField(max_length=256, verbose_name='\u540d\u524d')),
                ('description', models.CharField(default='', max_length=256, verbose_name='\u8aac\u660e')),
                ('initialized', models.BooleanField(default=False, verbose_name='\u521d\u671f\u5316\u6e08\u307f')),
            ],
        ),
    ]
