# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-18 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djatson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlerdata',
            name='keyword',
            field=models.CharField(default='', max_length=255, verbose_name='\u30ad\u30fc\u30ef\u30fc\u30c9'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='htmldata',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='\u30bf\u30a4\u30c8\u30eb'),
            preserve_default=False,
        ),
    ]
