# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-03 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djatson', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldata',
            name='initialized',
            field=models.BooleanField(default=False, editable=False, verbose_name='\u521d\u671f\u5316\u6e08\u307f'),
        ),
    ]
