# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-04 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djatson', '0003_urldata_ws_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urldata',
            name='initialized',
        ),
        migrations.AddField(
            model_name='urldata',
            name='state',
            field=models.CharField(choices=[('pending', '\u521d\u671f\u5316\u5f85\u3061'), ('initializing', '\u521d\u671f\u5316\u4e2d'), ('active', '\u6b63\u5e38'), ('error', '\u7570\u5e38')], default='pending', max_length=64, verbose_name='\u72b6\u614b'),
        ),
    ]
