# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-04 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djatson', '0004_auto_20180504_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldata',
            name='ws_id',
            field=models.CharField(default='', max_length=512, verbose_name='\u30ef\u30fc\u30af\u30b9\u30da\u30fc\u30b9ID'),
        ),
    ]
