# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-05 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djatson', '0005_auto_20180504_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldata',
            name='state',
            field=models.CharField(choices=[('pending', '\u521d\u671f\u5316\u5f85\u3061'), ('initializing', '\u521d\u671f\u5316\u4e2d'), ('active', '\u6b63\u5e38'), ('error', '\u7570\u5e38')], default='pending', editable=False, max_length=64, verbose_name='\u72b6\u614b'),
        ),
        migrations.AlterField(
            model_name='urldata',
            name='ws_id',
            field=models.CharField(default='', editable=False, max_length=512, verbose_name='\u30ef\u30fc\u30af\u30b9\u30da\u30fc\u30b9ID'),
        ),
    ]
