# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-11 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djatson', '0008_auto_20180508_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldata',
            name='selector',
            field=models.CharField(blank=True, editable=False, max_length=128, verbose_name='\u5bfe\u8c61CSS\u30bb\u30ec\u30af\u30bf(\u30aa\u30d7\u30b7\u30e7\u30f3)'),
        ),
    ]
