# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-05 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djatson', '0009_auto_20180511_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldata',
            name='description',
            field=models.CharField(default='', max_length=255, verbose_name='\u8aac\u660e'),
        ),
        migrations.AlterField(
            model_name='urldata',
            name='name',
            field=models.CharField(max_length=255, verbose_name='\u540d\u524d'),
        ),
    ]
